CXXFLAGS = -std=c++11
CC = g++

#TARGET = access_inherit override_overload
TARGET = override_overload virtual_destructor smp_unique smp_shared

all: $(TARGET)

.PHONY: clean

clean:
	rm -f $(TARGET) *.o *~
