objects = vector_length.o Vector3D.o

CXXFLAGS = -std=c++11
vector_length: $(objects)
	g++ -o vector_length $(objects)

vector_length.o: vector_length.cc
Vector3D.o: Vector3D.cc

.PHONY: clean
clean:
	rm -f vector_length $(objects) *~
