CXXFLAGS = -std=c++11
CC = g++

TARGET = fact static_objects swap_with_pointer swap_with_reference func_return lvalue_return list_return recurs_fact

all: $(TARGET)

.PHONY: clean

clean:
	rm -f $(TARGET) *.o *~
